nome=input('qual o seu nome?')
print('bem-vindo ao python', nome, '!')
print ('gostaria de realizar algumas perguntas, tudo bem?')
print('vamos lá!')
idade=input('quantos anos você tem?')
print(idade, 'ta velho viu hahaha')
desejo=input('tem vontade de aprender o python?')
motivo=input('por qual motivo?')
print('motivo interessante,', nome, '!')
print('isso é tudo, até outra hora')
